### ISSUE TITLE
Strange behavior: \w* and backreferences

### ISSUE THREAD

**Issue by Skif-off** [masterandrey/TRegExpr#5]
```Pascal
uses RegExpr;
begin
  WriteLn( ReplaceRegExpr('(\w*)','name.ext','$1.new', True) );
  ReadLn;
end.
```
Return: `name.new.new.ext.new.new`. Bug or incorrect use?

On Russian: некоторые подробности проблемы [отсюда](https://doublecmd.sourceforge.io/forum/viewtopic.php?p=20912#p20912) и ниже.

**Comment by masterandrey** [comment]
https://github.com/masterandrey/TRegExpr/commit/1e2cd9e007c8b2f7593d847999c6ccb8ff3c58bc

Strange but expected behaviour or replace function.
It repeats r.e. search till the end of the string.
1) Find 'name', replace with name.ext
2) Start searching from '.' and finds zero chars as correct result of \w*, so add '.ext'
3) Start after '.' and finds 'ext' and replace it with 'ext.new'
4) And final search at the end of the string also success with empty string so add '.new'

Replace '*' with '+' and it would not get empty string as correct one - I think i any case you are ont interested in empty file names.

**Comment by Skif-off** [comment]
> I think in any case you are not interested in empty file names.

Yes, of course :) It's a artificial situation, but I thought: maybe it's inaccuracy and it can be problem in some real cases? And reported. (I'm not an expert of regular expressions, I use them little-by-little.)
Thank you!
